// <auto-generated />
using HotelEngine;
using HotelModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HotelModel.Migrations
{
    [DbContext(typeof(HbgModel))]
    partial class HbgModelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("HotelEngine.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("BuildingCost");

                    b.Property<int?>("HotelObjId");

                    b.Property<decimal>("PricePerNight");

                    b.HasKey("Id");

                    b.HasIndex("HotelObjId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("HotelEngine.EntrancePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameLogicPersistenceId");

                    b.Property<int>("Position");

                    b.Property<int>("Side");

                    b.HasKey("Id");

                    b.HasIndex("GameLogicPersistenceId");

                    b.ToTable("EntrancePosition");
                });

            modelBuilder.Entity("HotelEngine.GameLogicPersistence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActivePlayerID");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("HotelEngine.HbgColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.HasKey("Id");

                    b.ToTable("HbgColor");
                });

            modelBuilder.Entity("HotelEngine.HotelObj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cost");

                    b.Property<int>("CurrentCategory");

                    b.Property<decimal>("EntranceCost");

                    b.Property<string>("Name");

                    b.Property<int?>("OwnerId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("HotelObj");
                });

            modelBuilder.Entity("HotelEngine.Ownership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameLogicPersistenceId");

                    b.Property<int?>("HotelId");

                    b.Property<int>("OwnerID");

                    b.HasKey("Id");

                    b.HasIndex("GameLogicPersistenceId");

                    b.HasIndex("HotelId");

                    b.ToTable("Ownership");
                });

            modelBuilder.Entity("HotelEngine.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CanBuyEntrance");

                    b.Property<string>("ClrGridHtml");

                    b.Property<int>("CurrentPosition");

                    b.Property<int?>("GameLogicPersistenceId");

                    b.Property<decimal>("Money");

                    b.Property<string>("Name");

                    b.Property<int?>("PlaceholderColorId");

                    b.HasKey("Id");

                    b.HasIndex("GameLogicPersistenceId");

                    b.HasIndex("PlaceholderColorId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("HotelEngine.Category", b =>
                {
                    b.HasOne("HotelEngine.HotelObj")
                        .WithMany("Rate")
                        .HasForeignKey("HotelObjId");
                });

            modelBuilder.Entity("HotelEngine.EntrancePosition", b =>
                {
                    b.HasOne("HotelEngine.GameLogicPersistence")
                        .WithMany("EntrancePositions")
                        .HasForeignKey("GameLogicPersistenceId");
                });

            modelBuilder.Entity("HotelEngine.HotelObj", b =>
                {
                    b.HasOne("HotelEngine.Player", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("HotelEngine.Ownership", b =>
                {
                    b.HasOne("HotelEngine.GameLogicPersistence")
                        .WithMany("OwnerShips")
                        .HasForeignKey("GameLogicPersistenceId");

                    b.HasOne("HotelEngine.HotelObj", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId");
                });

            modelBuilder.Entity("HotelEngine.Player", b =>
                {
                    b.HasOne("HotelEngine.GameLogicPersistence")
                        .WithMany("Players")
                        .HasForeignKey("GameLogicPersistenceId");

                    b.HasOne("HotelEngine.HbgColor", "PlaceholderColor")
                        .WithMany()
                        .HasForeignKey("PlaceholderColorId");
                });
#pragma warning restore 612, 618
        }
    }
}
